### ISSUE TITLE
v0.3.5 regression: Module resolution error with Prisma-generated files

### ISSUE THREAD

**Issue by pheuter** [basementstudio/xmcp#224]
## Description

Version 0.3.5 introduces a module resolution regression that breaks compatibility with Prisma-generated client files. The server fails to start when importing Prisma clients due to strict ESM resolution requiring explicit file extensions.

## Error Message

```
[HTTP-server] Error handling MCP request: Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'generated/enums' imported from generated/client.ts
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
```

## Root Cause

Prisma generates TypeScript client files with relative imports lacking file extensions:

```typescript
// In generated/client.ts
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"
```

While these imports work in v0.3.4, v0.3.5's stricter module resolution (likely related to the new SSR/hydration features) requires explicit extensions like `"./enums.js"` or `"./enums.ts"`.

## Steps to Reproduce

1. Create an xmcp server project
2. Add Prisma with `prisma generate` creating client files in a package
3. Import the Prisma client in a tool: `import { PrismaClient } from '@mypackage/server'`
4. Attempt to connect an MCP client to the server
5. Observe module resolution failure

## Expected Behavior

xmcp should resolve module imports without explicit file extensions, as done in v0.3.4, maintaining compatibility with common code generators like Prisma.

## Actual Behavior

Server throws `ERR_MODULE_NOT_FOUND` when loading Prisma-generated files with extension-less imports.

## Environment

- xmcp: 0.3.5
- Node.js: v22.20.0
- Bun: 1.3.1
- Prisma: 6.16.3+
- Platform: macOS (darwin)

## Workaround

Downgrade to xmcp 0.3.4:

```json
{
  "dependencies": {
    "xmcp": "0.3.4"
  }
}
```

## Additional Context

This regression likely stems from changes introduced in v0.3.5 for "SSR + Hydration feature" and "Structured Content output" support. The new bundling/resolution strategy appears to enforce stricter ESM compliance.

Since Prisma is a widely-used ORM that generates code this way (and cannot be easily configured to add extensions), this breaks a common use case for MCP servers that need database access.

**Comment by valebearzotti** [comment]
hey @pheuter !
when we added the React feature, we didn’t change webpack's module resolution at all
I tried reproducing the bug in this project: https://github.com/valebearzotti/prisma, but both version 0.3.5 and the latest 0.3.6 canary work fine for me
could you share a few more details about your project setup?

**Comment by pheuter** [comment]
@valebearzotti It appears to be fixed in v0.3.6!
